language: c
compiler:
  - gcc
  - clang
install: sudo apt-get install libsnappy-dev zlib1g-dev
#install: sudo apt-get install liblz4-dev libsnappy-dev zlib1g-dev
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make && make test
